name: Build Pib image on RaspianOS

on:
        push:

jobs:
        build:
                - name: Checkout CustomPiOS
                  uses: actions/checkout@v4
                  with:
                          repository: 'guysoft/CustomPiOS'
                          path: CustomPiOS
                - name: Checkout Project Repository
                  uses: actions/checkout@v4
                  with:
                          path: repository
                          submodules: true
